"""add ai_actions table and merchant tool-ordering flag

Revision ID: 07adae190eec
Revises: 27e5ce804847
Create Date: 2026-08-25 18:48:46.518228

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07adae190eec"
down_revision: str | Sequence[str] | None = "27e5ce804847"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_actions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("merchant_id", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("message_id", sa.String(), nullable=False),
        sa.Column("action_type", sa.String(), nullable=False),
        sa.Column("arguments", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_actions_action_type"), "ai_actions", ["action_type"], unique=False)
    op.create_index(op.f("ix_ai_actions_conversation_id"), "ai_actions", ["conversation_id"], unique=False)
    op.create_index(op.f("ix_ai_actions_merchant_id"), "ai_actions", ["merchant_id"], unique=False)
    op.create_index(op.f("ix_ai_actions_message_id"), "ai_actions", ["message_id"], unique=False)
    op.create_index(op.f("ix_ai_actions_status"), "ai_actions", ["status"], unique=False)
    op.add_column(
        "merchants", sa.Column("ai_tool_ordering_enabled", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("merchants", "ai_tool_ordering_enabled")
    op.drop_index(op.f("ix_ai_actions_status"), table_name="ai_actions")
    op.drop_index(op.f("ix_ai_actions_message_id"), table_name="ai_actions")
    op.drop_index(op.f("ix_ai_actions_merchant_id"), table_name="ai_actions")
    op.drop_index(op.f("ix_ai_actions_conversation_id"), table_name="ai_actions")
    op.drop_index(op.f("ix_ai_actions_action_type"), table_name="ai_actions")
    op.drop_table("ai_actions")
    # ### end Alembic commands ###
