"""add clustered_at to messages

Revision ID: 0fe57d0d5041
Revises: fb2585d043c4
Create Date: 2026-08-23 08:08:30.839683

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0fe57d0d5041"
down_revision: str | Sequence[str] | None = "fb2585d043c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("clustered_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "clustered_at")
    # ### end Alembic commands ###
