"""add human handoff models and ai flags

Revision ID: 1fc35ea104f4
Revises: 42a2a7e31122
Create Date: 2026-08-29 12:53:26.091442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fc35ea104f4'
down_revision: Union[str, Sequence[str], None] = '42a2a7e31122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_handoffs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('reason', sa.Enum('USER_REQUEST', 'AI_ESCALATION', 'MERCHANT_TAKEOVER', name='handoffreason'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_handoffs_conversation_id'), 'human_handoffs', ['conversation_id'], unique=False)
    op.add_column('conversations', sa.Column('ai_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('conversations', sa.Column('human_takeover', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('merchants', sa.Column('ai_enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'ai_enabled')
    op.drop_column('conversations', 'human_takeover')
    op.drop_column('conversations', 'ai_enabled')
    op.drop_index(op.f('ix_human_handoffs_conversation_id'), table_name='human_handoffs')
    op.drop_table('human_handoffs')
    # ### end Alembic commands ###
