"""add message_id and escalation_reason to order

Revision ID: 278b7f901463
Revises: 1689c340b77d
Create Date: 2026-08-23 06:48:32.772450

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "278b7f901463"
down_revision: str | Sequence[str] | None = "1689c340b77d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("message_id", sa.String(), nullable=False))
    op.add_column("orders", sa.Column("escalation_reason", sa.String(), nullable=True))
    op.create_index(op.f("ix_orders_conversation_id"), "orders", ["conversation_id"], unique=False)
    op.create_index(op.f("ix_orders_escalation_reason"), "orders", ["escalation_reason"], unique=False)
    op.create_index(op.f("ix_orders_message_id"), "orders", ["message_id"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_foreign_key(None, "orders", "messages", ["message_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_message_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_escalation_reason"), table_name="orders")
    op.drop_index(op.f("ix_orders_conversation_id"), table_name="orders")
    op.drop_column("orders", "escalation_reason")
    op.drop_column("orders", "message_id")
    # ### end Alembic commands ###
