"""Migration

Revision ID: 4c5c72d54bc9
Revises: ee5c64df2d8d
Create Date: 2026-09-04 08:45:01.151855

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c5c72d54bc9"
down_revision: str | Sequence[str] | None = "ee5c64df2d8d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("channel_connections", sa.Column("account_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("channel_connections", "account_name")
    # ### end Alembic commands ###
