"""add carts and cart_items

Revision ID: 59f0a9f00cb5
Revises: fa4b4edfbfea
Create Date: 2026-08-25 23:05:23.487019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59f0a9f00cb5'
down_revision: Union[str, Sequence[str], None] = 'fa4b4edfbfea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CHECKED_OUT', name='cartstatus'), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carts_conversation_id'), 'carts', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_carts_merchant_id'), 'carts', ['merchant_id'], unique=False)
    op.create_index('uq_carts_one_active_per_conversation', 'carts', ['conversation_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('cart_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cart_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'product_id', name='uq_cart_items_cart_product')
    )
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cart_items_product_id'), 'cart_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_cart_items_product_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index('uq_carts_one_active_per_conversation', table_name='carts', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_carts_merchant_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_conversation_id'), table_name='carts')
    op.drop_table('carts')
    # ### end Alembic commands ###
